# Generated by Django 2.1.3 on 2018-12-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20181203_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code_borrow',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
