# Generated by Django 2.1.3 on 2018-12-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20181203_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code_borrow',
            field=models.UUIDField(blank=True, default='23C82E', null=True, unique=True),
        ),
    ]
