# Generated by Django 2.1.3 on 2018-12-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20181203_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code_borrow',
            field=models.CharField(blank=True, default='A41065', max_length=8, null=True, unique=True),
        ),
    ]
