# Generated by Django 2.1.3 on 2018-12-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20181203_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code_borrow',
            field=models.CharField(blank=True, default='9C26CC', max_length=8, null=True, unique=True),
        ),
    ]
