# Generated by Django 2.1.3 on 2018-12-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20181204_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code_borrow',
            field=models.CharField(blank=True, default='C7B142', max_length=8, null=True, unique=True),
        ),
    ]
