# Generated by Django 2.1.3 on 2018-12-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20181204_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code_borrow',
            field=models.CharField(blank=True, default='CDD7AB', max_length=8, null=True, unique=True),
        ),
    ]
