# Generated by Django 2.1.3 on 2018-12-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20181204_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='code_borrow',
            field=models.CharField(blank=True, default='5A9810', max_length=8, null=True, unique=True),
        ),
    ]
